apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-cicd-app
  template:
    metadata:
      labels:
        app: devops-cicd-app
    spec:
      containers:
        - name: devops-cicd-app
          image: docker-registry:5000/devops-cicd-app:latest
          imagePullPolicy: Always
